name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        id: cache
        with:
          path: target/release/cmranking
          key: ${{ hashFiles('./Cargo.toml', './src/**') }}

      - name: Release build
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo build --release

      - name: Release run
        run: ./target/release/cmranking

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
